export const exampleTracks = [
  {
    kind: 'track',
    id: 433098966,
    created_at: '2018/04/21 16:16:30 +0000',
    user_id: 45263,
    duration: 3570410,
    commentable: true,
    state: 'finished',
    original_content_size: 142803136,
    last_modified: '2018/04/26 15:44:22 +0000',
    sharing: 'public',
    tag_list:
      'DJ Set Mix Mixtape Dj-Set DJSet Music Techno House Techhouse Deephouse Producer Mixing Musik EDM Dance Germany Deep Live Festival Radio Show Radioshow Radioset Gabriel Ananda gabrielananda soulful soulfultechno techno',
    permalink: 'gabriel-ananda-presents-souflul-techno-64',
    streamable: true,
    embeddable_by: 'all',
    downloadable: false,
    purchase_url: null,
    label_id: null,
    purchase_title: null,
    genre: 'Soulful Techno',
    title: 'Gabriel Ananda - Gabriel Ananda Presents Souflul Techno 64',
    description:
      '#64\n\n01.\tGullen - Bridget´s Eternity\n02.\tMees Salome - Ya Amar\n03.\tDeeparture - Apron (Mohn Remix)\n04.\tBetoko - Foreverness (Gabriel Ananda Remix)\n05.\tFoto - Chemicals\n06.\tMike Thor - Winter Lakes\n07.\tMiyaki - When You Wisper\n08.\tActive Child - Johnny Belinda (Dave DK Pacific Coast Instrumental)\n09.\tBicep - Opal (Four Tet Remix)\n10.\tDitian, Kevin Di Serna - Crystal Forest\n11.\tTheo Fråga, Klaus Kim - Cordas\n\nIf you want to broadcast the mix, please contact jannik@artist-one.com',
    label_name: null,
    release: null,
    track_type: null,
    key_signature: null,
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'mp3',
    license: 'all-rights-reserved',
    uri: 'https://api.soundcloud.com/tracks/433098966',
    user: {
      id: 45263,
      kind: 'user',
      permalink: 'gabrielananda',
      username: 'Gabriel Ananda',
      last_modified: '2018/04/22 16:02:06 +0000',
      uri: 'https://api.soundcloud.com/users/45263',
      permalink_url: 'http://soundcloud.com/gabrielananda',
      avatar_url: 'https://i1.sndcdn.com/avatars-000228476000-odvlb3-large.jpg'
    },
    attachments_uri: 'https://api.soundcloud.com/tracks/433098966/attachments',
    permalink_url:
      'http://soundcloud.com/gabrielananda/gabriel-ananda-presents-souflul-techno-64',
    artwork_url: 'https://i1.sndcdn.com/artworks-000338175024-chpvrv-large.jpg',
    waveform_url: 'https://w1.sndcdn.com/ksJhnkcjU2PY_m.png',
    stream_url: 'https://api.soundcloud.com/tracks/433098966/stream',
    playback_count: 0,
    download_count: 0,
    favoritings_count: 742,
    comment_count: 56
  },
  {
    kind: 'track',
    id: 444236124,
    created_at: '2018/05/15 06:49:00 +0000',
    user_id: 4758903,
    duration: 3240792,
    commentable: true,
    state: 'finished',
    original_content_size: 571613036,
    last_modified: '2018/05/15 10:05:53 +0000',
    sharing: 'public',
    tag_list: '"tech house"',
    permalink: 'total-mass-retain',
    streamable: true,
    embeddable_by: 'all',
    downloadable: true,
    purchase_url: null,
    label_id: null,
    purchase_title: null,
    genre: 'Techno',
    title: 'Total Mass Retain',
    description:
      'My hat in the ring for consideration for the FnF 2018 summer campout.\n <3',
    label_name: null,
    release: null,
    track_type: null,
    key_signature: null,
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'wav',
    license: 'all-rights-reserved',
    uri: 'https://api.soundcloud.com/tracks/444236124',
    user: {
      id: 4758903,
      kind: 'user',
      permalink: 'kikipopo',
      username: 'kikipopo',
      last_modified: '2018/04/13 21:43:41 +0000',
      uri: 'https://api.soundcloud.com/users/4758903',
      permalink_url: 'http://soundcloud.com/kikipopo',
      avatar_url: 'https://i1.sndcdn.com/avatars-000016151775-6ntjhs-large.jpg'
    },
    attachments_uri: 'https://api.soundcloud.com/tracks/444236124/attachments',
    permalink_url: 'http://soundcloud.com/kikipopo/total-mass-retain',
    artwork_url: 'https://i1.sndcdn.com/artworks-000348445347-lfrgma-large.jpg',
    waveform_url: 'https://w1.sndcdn.com/00L8UKsLv66k_m.png',
    stream_url: 'https://api.soundcloud.com/tracks/444236124/stream',
    download_url: 'https://api.soundcloud.com/tracks/444236124/download',
    playback_count: 0,
    download_count: 4,
    favoritings_count: 11,
    comment_count: 2
  },
  {
    kind: 'track',
    id: 436755582,
    created_at: '2018/04/29 09:09:41 +0000',
    user_id: 26584,
    duration: 7179042,
    commentable: true,
    state: 'finished',
    original_content_size: 286886117,
    last_modified: '2018/04/29 09:31:44 +0000',
    sharing: 'public',
    tag_list: 'Unison LoQuai "Frisky Radio" 12 04 2018',
    permalink: 'unison-030-hby-loquai-at-frisky-radio-12042018',
    streamable: true,
    embeddable_by: 'all',
    downloadable: false,
    purchase_url: null,
    label_id: null,
    purchase_title: null,
    genre: 'Deep/Tech/Techno/Progressive House',
    title: 'Unison 030 H/by LoQuai at Frisky Radio 12/04/2018',
    description:
      "Stiven_Rivic,_Michael_&_Levan_-_Nostalgia_(Plus_Thirty_Remix)\nGovinda_(Arg)_-_Por_Las_Noches_(Original_Mix)\nCryptic_Realms_-_Inside_Of_You_(Alec_Araujo_Remix)\nHasith_-_Lysithea_(A-Jay_(SL)_Remix)\nParallel_Universe_-_Deep_Space_(Original_Mix)\nNairo,_Sarcasmo_-_Elysium_(Original_Mix)\nSpuri_-_Khaleesi_(Stereo_Underground_Remix)\nJulian_Morbelli_-_Slow_Burning_(Original_Mix)\nLovewithme_-_Flood_(Original_Mix)\nMartin_Merkel_-_Afterlife_(Original_Mix)\nHot_Tuneik,_OneTwo_(Mx)_-_O'Girondo_(K_Nass_Remix)\nHenrike_-_Major_Seven_(Original_Mix)\nGeorge_X_-_Nahuati_(Original_Mix)\nTim_Penner_-_Lost_Again_(Stendahl_Remix)\nSubconcious_Tales_&_The_Chemical_Brothers_-_It_Was_&_It_Will_Be_Out_Of-Control_(amhain_&_Silinder_Edit)\nMatan_Caspi_-_Home_(Original_Mix)\nRusslan_Jaafreh_-_Algorithm_(Original_Mix)\nNorman_H,_Julie_Mintz_-_Flying_Away_(Alfonso_Muchacho_Remix)\nMichael_A_-_Aura_Tears_(Original_Mix)\nKyka_-_Horizon_(Oliver_Petkovski_Remix)",
    label_name: null,
    release: null,
    track_type: null,
    key_signature: null,
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'mp3',
    license: 'all-rights-reserved',
    uri: 'https://api.soundcloud.com/tracks/436755582',
    user: {
      id: 26584,
      kind: 'user',
      permalink: 'loquai',
      username: 'LoQuai',
      last_modified: '2018/04/29 09:42:55 +0000',
      uri: 'https://api.soundcloud.com/users/26584',
      permalink_url: 'http://soundcloud.com/loquai',
      avatar_url: 'https://i1.sndcdn.com/avatars-000337705832-9ar210-large.jpg'
    },
    attachments_uri: 'https://api.soundcloud.com/tracks/436755582/attachments',
    permalink_url:
      'http://soundcloud.com/loquai/unison-030-hby-loquai-at-frisky-radio-12042018',
    artwork_url: null,
    waveform_url: 'https://w1.sndcdn.com/0kzJD2PjTsPR_m.png',
    stream_url: 'https://api.soundcloud.com/tracks/436755582/stream',
    playback_count: 0,
    download_count: 0,
    favoritings_count: 76,
    comment_count: 3
  },
  {
    kind: 'track',
    id: 430022226,
    created_at: '2018/04/15 14:29:19 +0000',
    user_id: 15713796,
    duration: 3522131,
    commentable: true,
    state: 'finished',
    original_content_size: 141099994,
    last_modified: '2018/04/26 03:09:26 +0000',
    sharing: 'public',
    tag_list: '"Afterhour Sounds " Californien Deep',
    permalink: 'atish-presents-afterhour-sounds-podcast-nr-134',
    streamable: true,
    embeddable_by: 'all',
    downloadable: false,
    purchase_url: 'https://theartistunion.com/tracks/06ec78',
    label_id: null,
    purchase_title: 'download',
    genre: 'atish',
    title: 'atish presents Afterhour Sounds Podcast Nr. 134',
    description:
      '© artwork by franz zünkler ➲ contact ✉ franz.zuenkler@t-online.de\n\nAtish (https://soundcloud.com/atish) presents Afterhour Sounds Podcast Nr.134\n\nUnsere Nr. 134 kommt heute von einem amerikanischen Künstler, der mich seit 3 Jahren ununterbrochen musikalisch begleitet. Ich erinnere mich noch sehr gut an seine damalige Bunring Man Aufnahme… Sie haute mich schlichtweg um. Seitdem komme ich nicht mehr um Ihn herum. \n\nDie Rede ist von „Atish“, einem ehrlichen und unkomplizierten Künstler, der keinen geradlinigen Weg ging. Anfangs noch Programmierer für Facebook, entschied er sich vor knapp 10 Jahren selber Musik zu mixen, wie seine unzähligen Mixe belegen. Anders als viele andere Künstler, die gerne ihre so genannte ‚peinliche‘ Anfangszeit verheimlichen möchten, sind bei Ihm tatsächlich noch alle Mixe zum Anhören verfügbar. Dass er damals wie heute seinem Sound gleich geblieben ist, spricht umso mehr für diesen sympathischen Menschen. \n\nSein Coming Out hatte er 2012, als er auf dem Robot Heart art-car spielte. Seitdem ging es steil bergauf. Tokio, New York, Istanbul, Berlin,…um nur einige Stationen seines vollgepackten Kalenders zu nennen.\n\nAber auch in seiner Wahlstadt San Francisco treibt er weiterhin sein Unwesen. Und wie!!! Neben dem etwas anderen Clubformat mit dem Namen ‚Late night tonight!‘, einer Mischung aus Talk-Show und Club Party, gründete er auch das Label ‚Manjumasi‘. \nUnd wäre dies nicht schon genug, feilt er in jeder freien Minute an kommenden Releases und Remixen. Tendenz steigend. Sowohl in Qualität, als auch in Quantität. Wir sind gespannt.\n\nDas von Ihm eingespielte Set ist eine herrlich ‚afterhoureske‘ Reise ins Dickicht der melodischen und verträumten elektronischen Musik. Das sich Atish für dieses Set etwas ganz besonderes einfallen lassen hat ist unüberhörbar. Ich war beim ersten Hören des Sets tatsächlich komplett geflasht, hatte ich doch etwas anderes erwartet. Aber diese Überraschungsmomente, die unsere Reihe und die jeweiligen musikalischen Interpretationen immer wieder mit sich bringen, hauen mich, nein uns, immer wieder um. Darauf darf man auch ein wenig Stolz sein. Vor allem wenn man am Ende ein ganz außergewöhnliches Set erhält. So auch hier. Schnallt euch an… Ich kann mich nur wiederholen, aber es erwartet euch eine Reise durch verspielte, sehr deepe und hypnothische Felder, wie gemacht für eine tanzbare Afterhour sind. Das gabs bei uns schon lange nicht mehr….seid gespannt.\n\nWir danken Dir vielmals für dieses besondere Set Atish. Umwerfend und überraschend gut. Wenn Unikat, dann Hier. Chapeu.\n\nWir sind entzückt.\n\n✘ Atish (San Francisco/United States Of America)\n\nsoundcloud.com/atish\nfacebook.com/atishmusic\n\nTRACKLIST | bit.ly/atish-afterhour',
    label_name: null,
    release: null,
    track_type: null,
    key_signature: null,
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'mp3',
    license: 'all-rights-reserved',
    uri: 'https://api.soundcloud.com/tracks/430022226',
    user: {
      id: 15713796,
      kind: 'user',
      permalink: 'afterhour-sounds',
      username: 'Afterhour Sounds',
      last_modified: '2018/05/23 12:49:49 +0000',
      uri: 'https://api.soundcloud.com/users/15713796',
      permalink_url: 'http://soundcloud.com/afterhour-sounds',
      avatar_url: 'https://i1.sndcdn.com/avatars-000278226969-cnwwnw-large.jpg'
    },
    attachments_uri: 'https://api.soundcloud.com/tracks/430022226/attachments',
    permalink_url:
      'http://soundcloud.com/afterhour-sounds/atish-presents-afterhour-sounds-podcast-nr-134',
    artwork_url: 'https://i1.sndcdn.com/artworks-000335493165-yb1tzm-large.jpg',
    waveform_url: 'https://w1.sndcdn.com/4TsPUdbGz4Dt_m.png',
    stream_url: 'https://api.soundcloud.com/tracks/430022226/stream',
    playback_count: 0,
    download_count: 40,
    favoritings_count: 2900,
    comment_count: 175
  },
  {
    kind: 'track',
    id: 426386232,
    created_at: '2018/04/08 00:31:04 +0000',
    user_id: 7742327,
    duration: 6829282,
    commentable: true,
    state: 'finished',
    original_content_size: 239631918,
    last_modified: '2018/05/09 18:00:45 +0000',
    sharing: 'public',
    tag_list: '"Progressive House" "Deep Tech" "Deep Techno" "Deep House"',
    permalink: '4am-sessions-003',
    streamable: true,
    embeddable_by: 'all',
    downloadable: true,
    purchase_url: null,
    label_id: null,
    purchase_title: null,
    genre: 'Techno',
    title: '4am Sessions 003',
    description: '',
    label_name: null,
    release: null,
    track_type: null,
    key_signature: null,
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'm4a',
    license: 'cc-by-nc-sa',
    uri: 'https://api.soundcloud.com/tracks/426386232',
    user: {
      id: 7742327,
      kind: 'user',
      permalink: 'aarondysonxavier',
      username: 'Dyson',
      last_modified: '2018/04/09 15:04:33 +0000',
      uri: 'https://api.soundcloud.com/users/7742327',
      permalink_url: 'http://soundcloud.com/aarondysonxavier',
      avatar_url: 'https://i1.sndcdn.com/avatars-000419889066-y3uvlf-large.jpg'
    },
    attachments_uri: 'https://api.soundcloud.com/tracks/426386232/attachments',
    permalink_url: 'http://soundcloud.com/aarondysonxavier/4am-sessions-003',
    artwork_url: 'https://i1.sndcdn.com/artworks-000331476057-86odx9-large.jpg',
    waveform_url: 'https://w1.sndcdn.com/51IYO4r8Ou1h_m.png',
    stream_url: 'https://api.soundcloud.com/tracks/426386232/stream',
    download_url: 'https://api.soundcloud.com/tracks/426386232/download',
    playback_count: 0,
    download_count: 3,
    favoritings_count: 21,
    comment_count: 6
  },
  {
    kind: 'track',
    id: 414913206,
    created_at: '2018/03/17 02:40:24 +0000',
    user_id: 2625415,
    duration: 4442772,
    commentable: true,
    state: 'finished',
    original_content_size: 177819599,
    last_modified: '2018/03/20 15:52:39 +0000',
    sharing: 'public',
    tag_list: '',
    permalink: 'dynamite',
    streamable: true,
    embeddable_by: 'all',
    downloadable: true,
    purchase_url: null,
    label_id: null,
    purchase_title: null,
    genre: 'House',
    title: 'Dynamite',
    description:
      "Peak-hour house tunes that are dy-no-mite!!! Driving basslines, classic stylings, old skool vocals, all mixed in kem's signature style. A nice collection of material I've really enjoyed playing at gigs in 2018.",
    label_name: null,
    release: null,
    track_type: null,
    key_signature: null,
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'mp3',
    license: 'all-rights-reserved',
    uri: 'https://api.soundcloud.com/tracks/414913206',
    user: {
      id: 2625415,
      kind: 'user',
      permalink: 'kem_sf',
      username: 'Kem SF',
      last_modified: '2018/03/20 17:55:51 +0000',
      uri: 'https://api.soundcloud.com/users/2625415',
      permalink_url: 'http://soundcloud.com/kem_sf',
      avatar_url: 'https://i1.sndcdn.com/avatars-000281234877-uu4c5q-large.jpg'
    },
    attachments_uri: 'https://api.soundcloud.com/tracks/414913206/attachments',
    permalink_url: 'http://soundcloud.com/kem_sf/dynamite',
    artwork_url: 'https://i1.sndcdn.com/artworks-000317874195-kvgdnw-large.jpg',
    waveform_url: 'https://w1.sndcdn.com/qcAonyLajX86_m.png',
    stream_url: 'https://api.soundcloud.com/tracks/414913206/stream',
    download_url: 'https://api.soundcloud.com/tracks/414913206/download',
    playback_count: 0,
    download_count: 7,
    favoritings_count: 46,
    comment_count: 16
  },
  {
    kind: 'track',
    id: 415885806,
    created_at: '2018/03/19 07:16:31 +0000',
    user_id: 171569277,
    duration: 7913440,
    commentable: true,
    state: 'finished',
    original_content_size: 283251787,
    last_modified: '2018/05/15 04:59:54 +0000',
    sharing: 'public',
    tag_list: '"Deep House"',
    permalink: 'minor-wheel-vol-1',
    streamable: true,
    embeddable_by: 'all',
    downloadable: false,
    purchase_url: null,
    label_id: null,
    purchase_title: null,
    genre: 'Deep House',
    title: 'Minor Wheel Vol. I',
    description:
      'MelleM here, and Hello World! It’s been a long time in the making…but I’m happy to announce that I finally completed my VERY FIRST DJ SET!! :) I give you the Minor Wheel Vol. I.\n\nThe overall theme for this set presented itself to me in early 2017, and for the music geeks out there, the Minor Wheel series is an exploration of the beloved Camelot Wheel. For Vol. I, I start at G Minor / 6A…and loop completely around the wheel (minor keys only). You will hear anywhere from 2-4 tracks per key, ending back at G Minor where I started. There is absolutely no skipping of keys along the wheel, and no major keys are used. \n\nIt’s been quite an ambitious and loopy journey making the Minor Wheel Vol. I (pardon the pun). I’ve poured a ton of passion, knowledge, time, and even moments of obsession getting my debut set to a point where I was happy releasing it. It’s an incredibly emotional and magical set for me. Deep, lush, lyrical, evocative, and even a bit melancholic at times…with just enough mistakes here and there for my DJ friends to notice. This takes training wheels to a whole other level. ;)\n\nThanks for listening. Enjoy, and I welcome all comments and feedback!\n\nController: Traktor Kontrol S4 (2 decks)\nSoftware: rekordbox',
    label_name: null,
    release: null,
    track_type: null,
    key_signature: null,
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'm4a',
    license: 'all-rights-reserved',
    uri: 'https://api.soundcloud.com/tracks/415885806',
    user: {
      id: 171569277,
      kind: 'user',
      permalink: 'mellem-sf',
      username: 'MelleM',
      last_modified: '2018/05/19 17:17:52 +0000',
      uri: 'https://api.soundcloud.com/users/171569277',
      permalink_url: 'http://soundcloud.com/mellem-sf',
      avatar_url: 'https://i1.sndcdn.com/avatars-000412131822-e61cky-large.jpg'
    },
    attachments_uri: 'https://api.soundcloud.com/tracks/415885806/attachments',
    permalink_url: 'http://soundcloud.com/mellem-sf/minor-wheel-vol-1',
    artwork_url: 'https://i1.sndcdn.com/artworks-000318963321-qtx9ca-large.jpg',
    waveform_url: 'https://w1.sndcdn.com/ovPzQryfTsVs_m.png',
    stream_url: 'https://api.soundcloud.com/tracks/415885806/stream',
    playback_count: 0,
    download_count: 0,
    favoritings_count: 56,
    comment_count: 27
  }
];
